query ($name: String) {
    Page (page: 1, perPage: 30) {
        media (search: $name, type: ANIME) {
            id,
            title {
                romaji
            },
            episodes,
            relations {
                edges {
                    relationType,
                    node {
                        id
                    }
                }
            }
        }
    }
}