mutation (
    $mediaId: Int!,
    $watched_eps: Int!,
    $score: Float!,
    $status: MediaListStatus!,
    $times_rewatched: Int!,
    $start_date: FuzzyDateInput,
    $finish_date: FuzzyDateInput) {

    SaveMediaListEntry (
        mediaId: $mediaId,
        progress: $watched_eps,
        scoreRaw: $score,
        status: $status,
        repeat: $times_rewatched,
        startedAt: $start_date,
        completedAt: $finish_date) {
            
        mediaId
    }
}