REPLACE INTO AnimeEntry (
    id,
    watched_episodes,
    score,
    status,
    times_rewatched,
    start_date,
    finish_date,
    needs_sync
)
VALUES
    (
        :id,
        :watched_episodes,
        :score,
        :status,
        :times_rewatched,
        :start_date,
        :finish_date,
        :needs_sync
    )