query ($name: String!) {
    Page (page: 1, perPage: 30) {
        media (search: $name, type: ANIME) {
            id,
            title {
                romaji,
                userPreferred
            },
            episodes,
            duration,
            format,
            relations {
                edges {
                    relationType,
                    node {
                        id,
                        format
                    }
                }
            }
        }
    }
}